### PR TITLE
Assume ". src/ test/" when invoked without args

### PR DESCRIPTION
**Pull request by sol**

### CODE REVIEW

**Comment by sol** [comment]
@karun012 Feel free to modify to your liking.

**Comment by mwotton** [comment]
No fix for "argumets"?

**Comment by karun012** [comment]
Arguments?

**Comment by mwotton** [comment]
Spelling is wrong in the commit

**Comment by sol** [comment]
Apparently I was in a rush...

**Comment by karun012** [comment]
If it's the help text I've fixed it :)

**Comment by sol** [comment]
:)

**Comment by karun012** [comment]
@sol I listed your name in the readme without your permission. Hope you
don't mind.

**Pull request merged**
