### PR TITLE
Compilation error

### PR DESCRIPTION
**Pull request by stites**
I was getting the following compile error, and figured it was a simple fix. Looks like `watchTree`, coming from `System.FSNotify`, expects the `FilePath` from `IO`. In contrast, your `respondToEvent` receives an IO.FilePath and needs to convert it to a Filesystem.Path FilePath to be processed by the `eventHandler`.

I added a stack.yaml as well, just to get the ball rolling on this.

```
Configuring arion-0.1.0.8...
Building arion-0.1.0.8...
Preprocessing executable 'arion' for arion-0.1.0.8...
[1 of 6] Compiling Arion.Types      ( src/Arion/Types.hs, dist/build/arion/arion-tmp/Arion/Types.o )
[2 of 6] Compiling Arion.Utilities  ( src/Arion/Utilities.hs, dist/build/arion/arion-tmp/Arion/Utilities.o )
[3 of 6] Compiling Arion.Help       ( src/Arion/Help.hs, dist/build/arion/arion-tmp/Arion/Help.o )
[4 of 6] Compiling Arion.EventProcessor ( src/Arion/EventProcessor.hs, dist/build/arion/arion-tmp/Arion/EventProcessor.o )
[5 of 6] Compiling Arion.Runner     ( src/Arion/Runner.hs, dist/build/arion/arion-tmp/Arion/Runner.o )

src/Arion/Runner.hs:46:27:
    Couldn't match type ‘system-filepath-0.4.13.4:Filesystem.Path.Internal.FilePath’
                   with ‘[Char]’
    Expected type: FilePath
      Actual type: system-filepath-0.4.13.4:Filesystem.Path.Internal.FilePath
    In the second argument of ‘watchTree’, namely
      ‘(fromText $ pack path)’
    In a stmt of a 'do' block:
      _ <- watchTree
             manager
             (fromText $ pack path)
             (const True)
             (eventHandler
                lock
                inProgress
                (processEvent sourceToTestFileMap sourceFolder testFolder)
              . respondToEvent)
    In the expression:
      do { sourceFiles <- mapM
                            (\ x -> uncurry toSourceFile <$> filePathAndContent x)
                          =<< findHaskellFiles sourceFolder;
           testFiles <- mapM
                          (\ x -> uncurry toTestFile <$> filePathAndContent x)
                        =<< findHaskellFiles testFolder;
           let sourceToTestFileMap = associate sourceFiles testFiles;
           lock <- newEmptyMVar;
           .... }

src/Arion/Runner.hs:47:99:
    Couldn't match type ‘[Char]’
                   with ‘system-filepath-0.4.13.4:Filesystem.Path.Internal.FilePath’
    Expected type: fsnotify-0.2.1:System.FSNotify.Types.Event
                   -> Maybe
                        (system-filepath-0.4.13.4:Filesystem.Path.Internal.FilePath,
                         time-1.5.0.1:Data.Time.Clock.UTC.UTCTime)
      Actual type: fsnotify-0.2.1:System.FSNotify.Types.Event
                   -> Maybe (FilePath, time-1.5.0.1:Data.Time.Clock.UTC.UTCTime)
    In the second argument of ‘(.)’, namely ‘respondToEvent’
    In the fourth argument of ‘watchTree’, namely
      ‘(eventHandler
          lock
          inProgress
          (processEvent sourceToTestFileMap sourceFolder testFolder)
        . respondToEvent)’
```

### CODE REVIEW

**Comment by stites** [comment]
Oh, wow! I was also finding that there were four broken tests on `master` when I ran tests from my local box, so I was expecting travis to break.

**Comment by karun012** [comment]
Haven't been able to look into this. A little busy at the moment. Sorry.

**Comment by mwotton** [comment]
While there are still reasons to use arion if you aren't using stack, you
know that stack build --file-watch --test works, right?

**Comment by stites** [comment]
@mwotton — yup! I was just looking around at the code. There are still benefits to arion over stack as, from what I understand, you don't have to run the full test suite on each file change.

**Comment by karun012** [comment]
@stites I've merged your PR. I have been really busy with other work and haven't been able to look into adding Arion to stack. If you need anything from me, please do let me know.

**Pull request merged**
